/**
 * Non-homogeneous Poisson arrivals with an hour-of-day × day-of-week rate,
 * generated by thinning (Lewis & Shedler).
 */

import type { Rng } from './rng.js';

export interface ArrivalPattern {
  /** Patients per hour for each hour of the day, 24 entries. */
  hourlyRates: readonly number[];
  /** Multiplier per day of week, 7 entries, Monday first. */
  dayOfWeekMultipliers: readonly number[];
  startDayOfWeek: number;
  startHour: number;
}

const MINUTES_PER_WEEK = 7 * 24 * 60;

/** Arrival rate in patients per minute at sim time t (minutes). */
export function arrivalRatePerMinute(p: ArrivalPattern, t: number): number {
  const minuteOfWeek = (((p.startDayOfWeek * 24 + p.startHour) * 60 + t) % MINUTES_PER_WEEK + MINUTES_PER_WEEK) % MINUTES_PER_WEEK;
  const hourOfWeek = Math.floor(minuteOfWeek / 60);
  const day = Math.floor(hourOfWeek / 24);
  const hour = hourOfWeek % 24;
  return (p.hourlyRates[hour]! * p.dayOfWeekMultipliers[day]!) / 60;
}

export function maxArrivalRatePerMinute(p: ArrivalPattern): number {
  return (Math.max(...p.hourlyRates) * Math.max(...p.dayOfWeekMultipliers)) / 60;
}

export class ArrivalProcess {
  private readonly lambdaMax: number;

  constructor(
    private readonly pattern: ArrivalPattern,
    private readonly rng: Rng,
  ) {
    this.lambdaMax = maxArrivalRatePerMinute(pattern);
  }

  /** Time of the next arrival strictly after `from`, or undefined if none before `until`. */
  next(from: number, until: number): number | undefined {
    if (!(this.lambdaMax > 0)) return undefined;
    let t = from;
    for (;;) {
      t += this.rng.exponential(1 / this.lambdaMax);
      if (t >= until) return undefined;
      if (this.rng.next() * this.lambdaMax < arrivalRatePerMinute(this.pattern, t)) return t;
    }
  }
}
